site_name: МЦ Ваш Доктор
site_description: Многопрофильный медицинский центр в г. Каменск-Уральский
site_url: http://mc-vd.github.io

theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    # - toc.integrate
    - navigation.top
  custom_dir: overrides

plugins:
  - search
  - blog:
      blog_dir: news
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Специалисты
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
      # post_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     short: true
  - meta
  - tags
  # - rss:
  #     match_path: "blog/posts/.*"
  #     date_from_meta:
  #       as_creation: date.created
  #       as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mc-vd/mc-vd.github.io
      name: Этот сайт на Github
    - icon: fontawesome/brands/vk
      link: https://vk.com/mc_vd96
      name: Группа в VK
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/79041778683
      name: Связь через WhatsApp
    - icon: fontawesome/brands/telegram
      link: https://t.me/mc_vd_bot
      name: Связь через Telegram

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Главная: index.md
  - Новости:
     - news/index.md
     - news/tags.md
  - Запись: booking.md
  - Услуги: services.md
  - Врачи: nikolaenkoaa.md
  - Профиль: account.md
  - Теги: tags.md